apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fraud-detection-serving
  namespace: default
spec:
  predictor:
    containers:
      - name: kserve-container
        image: konglsh96/fraud-detection:serving
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi