apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-back
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fraud-detection-back
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.backend.port }}
  type: NodePort
  externalIPs:
    - {{ .Values.backend.ip }}
