apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-back
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-back
  template:
    metadata:
      labels:
        app: fraud-detection-back
    spec:
      containers:
        - name: fraud-detection-back
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
          env:
            - name: NAMESPACE
              value: "{{ .Values.namespace }}"
            - name: ISTIO_IP
              value: "{{ .Values.istio.ip }}"
            - name: ISTIO_PORT
              value: "{{ .Values.istio.port }}"
            - name: BACKEND_IP
              value: "{{ .Values.backend.ip }}"
            - name: BACKEND_PORT
              value: "{{ .Values.backend.port }}"
            - name: MYSQL_IP
              value: "{{ .Values.mysql.ip }}"
            - name: MYSQL_PORT
              value: "{{ .Values.mysql.port }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
            - name: MYSQL_DB
              value: "{{ .Values.mysql.db }}"
