apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fraud-detection-serving
  namespace: {{ .Values.namespace }}
spec:
  predictor:
    containers:
      - name: kserve-container
        image: konglsh96/fraud-detection:serving
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.serving.resources.limits.cpu }}
            memory: {{ .Values.serving.resources.limits.memory }}
          requests:
            cpu: {{ .Values.serving.resources.requests.cpu }}
            memory: {{ .Values.serving.resources.requests.memory }}